version: '2'
services:
  server:
    image: 'references-tictactoe'
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'
    depends_on:
      - 'postgres'
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5400:5432"
