version: '2'
services:
  server:
    image: 'valdimar94/references-tictactoe'
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PORT=80
    ports:
      - '80:80'
      - '8080:8080'
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
