version: '2'
services:
  server:
    image: 'valdimar94/references-tictactoe:${GIT_COMMIT}' #the image containing the app
    environment:
      - NODE_ENV=production #make it the production environment
      - PGPORT=5432 # the local postgres port created
      - PORT=80 #aws instance port, can also be used locally but an image running on the aws instance can only be accessed online by the ip address if the port is 80 as this is the port aws uses
    ports:
      - '80:80'
      - '8080:8080'
    depends_on:
      - postgres
  postgres:
    image: postgres #the image needed for docker compose with the valdimar94/reference-tictactoe
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
