version: '2'
services:
  server:
    image: 'valdimar94/references-tictactoe'
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PORT=8080
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'
      - '8080:8080'
    depends_on:
      - 'postgres'
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5400:5432"
