#!/bin/bash

set -e

yum update -y #update instances
yum install -y docker #install docker so images and containers can be run
service docker start #start docker
curl -L "https://github.com/docker/compose/releases/download/1.9.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose #need docker-compose to be able to run the .yaml file
chmod +x /usr/local/bin/docker-compose #make the docker-compose executable

exit 0
