#!/bin/bash

set -e

yum update -y
yum install -y docker
service docker start
curl -L "https://github.com/docker/compose/releases/download/1.9.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
yum install -y git-all
git clone https://github.com/valdimar94/reference-tictactoe.git
cd reference-tictactoe/
docker-compose up

exit 0
